kind: pipeline
name: default

steps:
  - name: stack build
    image: nitta-build:latest
    pull: if-not-exists
    commands:
      - stack build --test --haddock --copy-bins
      # - stack exec nitta-api-gen

  # - name: npm build
  #   image: nitta-build:latest
  #   pull: if-not-exists
  #   commands:
  #     - cd web
  #     - npm install --dev
  #     - npm run build

  - name: success-telegram-notify
    image: byrnedo/alpine-curl
    commands:
      - export TIME="10"
      - export URL="https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
      - export CHAT_ID="-1001368976384"
      - export TEXT="build success branch '$DRONE_BRANCH' of '$DRONE_REPO_NAME'"
      - curl --socks5-hostname $SOCK5_HOST -U $SOCK5_AUTH --max-time $TIME -d "chat_id=$CHAT_ID&disable_web_page_preview=1&text=$TEXT" $URL
    when:
      status:
      - success
    environment:
      TELEGRAM_BOT_TOKEN:
        from_secret: TELEGRAM_BOT_TOKEN
      SOCK5_HOST:
        from_secret: SOCK5_HOST
      SOCK5_AUTH:
        from_secret: SOCK5_AUTH

  - name: failure-telegram-notify
    image: byrnedo/alpine-curl
    commands:
      - export TIME="10"
      - export URL="https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
      - export CHAT_ID="-1001368976384"
      - export TEXT="build failure branch '$DRONE_BRANCH' of '$DRONE_REPO_NAME'"
      - curl --socks5-hostname $SOCK5_HOST -U $SOCK5_AUTH --max-time $TIME -d "chat_id=$CHAT_ID&disable_web_page_preview=1&text=$TEXT" $URL
    when:
      status:
      - failure
    environment:
      TELEGRAM_BOT_TOKEN:
        from_secret: TELEGRAM_BOT_TOKEN
      SOCK5_HOST:
        from_secret: SOCK5_HOST
      SOCK5_AUTH:
        from_secret: SOCK5_AUTH
