# section for general parameters of template.
[template]
# subpath of nitta implementation (default: '.')
nittaPath = "."
# list of template files, which should be ignored (default: ['template.toml'])
ignore = ['template.toml']

# external signal names used in nitta instance
[signals]
rst = "rst"
clk = "clk"
